### ISSUE TITLE
[FEATURE REQUEST] Use ISO 8601 (RFC3339) timestamps in JSON body

### ISSUE THREAD

**Issue by stephanroosli** [TOMP-WG/TOMP-API#159]
Currently the timestamps in the API are defined as follows:

```
    timestamp:
      description: A UTC timestamp (number of milliseconds in a Date object since January
        1, 1970, 00:00:00)
      example: 1546336800
      type:
        number
```

Even though REST doesn't have a native datetime-format, I **suggest** here is to use a more human-readable format, based on ISO 8601/RFC 3339.

https://tools.ietf.org/html/rfc3339#section-5.6

from a related project in our company:
```
    timestamp:
      type: object
      description: '....'
      properties:
          type: string
          format: date-time
          example: '2020-06-28T14:55:00+02:00'
```
