### ISSUE TITLE
[FEATURE REQUEST] Required deeplink information

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#348]
## Is your feature request related to a problem? Please describe.
For creating deeplink information some extra information is needed when booking.

## Urgency

The deeplink is now not formalized in the TOMP-API, while it is the current state of the technique

## Describe the solution you'd like
Information has to be added to the booking object. The 'return url' (when exiting the 'deeplink app') has to be specified (is also a deeplink into the MP-app) and an 'error url' is needed (when an error occurs during the trip execution, you'll need a different deeplink into the MP-app).

## Possible Implementation
In the bookingrequest a new field has to be introduced. Since deeplinks can be provided per leg, this information is also per leg.
```
    bookingRequest:
      description: A booking requested by the MP
...
        legs:
          description: array for leg specific information
          type: array
          items:
            type: object
            properties:
              leg-id: 
                type: number
              deeplink-info:
                type: object
                properties:
                  returnUrl:
                    type: string
                    format: URI
                  errorUrl:
                    type: string
                    format: URI
```
