### ISSUE TITLE
[FEATURE REQUEST] Return URL for MP is different / not specified

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#349]
## Is your feature request related to a problem? Please describe.
The TO has to report events during the trip execution to the MP. The base URL to use is normally known by the TO (later: to be retrieved from the discovery service). But on some occasions the base URL is different.

## Describe the solution you'd like
Add a divergent base URL to the leg object. This has to be specified at the moment of booking. This issue is closely related to #348.

## Possible Implementation
```
    bookingRequest:
...
        legs:
          description: array for leg specific information
          type: array
          items:
            type: object
            properties:
              leg-id: 
                type: number
              base-url: 
                type: string
                format: URI
```
